language:
  java
jdk:
  - oraclejdk8

before_script:
  - sudo apt-get update
  - sudo apt-get install --only-upgrade -y oracle-java8-installer
  - pip install --user codecov

after_success:
  - codecov
